# Generated by Django 5.0.3 on 2024-05-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_uploadedfile_filedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
