# Generated by Django 5.0.3 on 2024-05-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_filedata_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeDriverLicenseDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=20)),
                ('valid_date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FakeIDCardDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.CharField(max_length=20)),
                ('doc_number', models.CharField(max_length=20)),
                ('ssn', models.CharField(max_length=20)),
            ],
        ),
    ]
