# Generated by Django 5.0.3 on 2024-05-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fakesatdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakedriverlicensedb',
            name='verdict',
            field=models.CharField(default='expired', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fakeidcarddb',
            name='verdict',
            field=models.CharField(default='expired', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fakesatdb',
            name='verdict',
            field=models.CharField(default='expired', max_length=20),
            preserve_default=False,
        ),
    ]
