# Generated by Django 5.0.3 on 2024-05-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_fakedriverlicensedb_verdict_fakeidcarddb_verdict_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakesatdb',
            name='unique_number',
            field=models.CharField(max_length=25),
        ),
    ]
