# Generated by Django 5.0.3 on 2024-05-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_fakesatdb_unique_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeidcarddb',
            name='issue_date',
            field=models.CharField(max_length=25),
        ),
    ]
